/**
 * Offline candidate pool for validating provenance reconstruction.
 *
 * SYNTHETIC. Every page lives on a reserved `.test` domain and is written for this fixture; none of
 * it quotes a real publication. It models the Cohen/Bard incident as the seed story, plus pages
 * designed to mislead: a backdated copy, an undated repost, an unrelated real-sounding case that
 * shares one party name, a different AI-citation incident, topical coverage without the
 * fabricated citations, and a later compilation with two plausible sources.
 *
 * Discovery reaches these pages only through CorpusSearch (keyword search) and outbound links,
 * exactly as it would reach real pages through Browserbase Search and Fetch.
 */

export interface CorpusPage {
  url: string;
  html: string;
  /** What a search engine would report as the publication date, if anything. */
  search_published?: string;
}

const FF = "United States v. Figueroa-Florez";
const OR = "United States v. Ortiz";
const AM = "United States v. Amato";

function page(opts: {
  title: string;
  site?: string;
  published?: string;
  jsonLdDate?: string;
  timeElement?: string;
  body: string;
}): string {
  const meta = [
    opts.site ? `<meta property="og:site_name" content="${opts.site}">` : "",
    opts.published ? `<meta property="article:published_time" content="${opts.published}">` : "",
    opts.jsonLdDate
      ? `<script type="application/ld+json">${JSON.stringify({
          "@context": "https://schema.org",
          "@type": "NewsArticle",
          headline: opts.title,
          datePublished: opts.jsonLdDate,
          publisher: opts.site ? { "@type": "Organization", name: opts.site } : undefined,
        })}</script>`
      : "",
  ].join("\n");
  return `<!doctype html><html><head><title>${opts.title}</title>${meta}</head>
<body><nav><a href="/">Home</a> <a href="/subscribe">Subscribe</a></nav>
<article><h1>${opts.title}</h1>
${opts.timeElement ? `<p><time datetime="${opts.timeElement}">${opts.timeElement.slice(0, 10)}</time></p>` : ""}
${opts.body}
</article></body></html>`;
}

export const CORPUS: CorpusPage[] = [
  // --- The propagation chain -------------------------------------------------------------
  {
    url: "https://exhibits.court-archive.test/cohen/exhibit-b-chatbot-response",
    html: page({
      title: "Exhibit B: chatbot response supplied by the defendant",
      site: "Court Exhibit Archive",
      published: "2023-11-25T14:00:00Z",
      body: `<p>Response generated by Google Bard when asked for appellate decisions on early termination of supervised release.</p>
<p>Several Second Circuit decisions support early termination: ${FF}, ${OR}, and ${AM}. In each, the court granted early termination where the defendant demonstrated sustained rehabilitation and comunity engagement after release.</p>`,
    }),
  },
  {
    url: "https://exhibits.court-archive.test/cohen/exhibit-c-email-to-counsel",
    html: page({
      title: "Exhibit C: email from the defendant to counsel",
      site: "Court Exhibit Archive",
      published: "2023-11-25T19:30:00Z",
      body: `<p>Forwarding the cases I found. ${FF}, ${OR}, and ${AM} all show sustained rehabilitation and comunity engagement after release.</p>
<p>These show judges ending supervision early for defendants with a clean record like mine, so please use them in the motion.</p>`,
    }),
  },
  {
    url: "https://dockets.court-archive.test/cohen/18-cr-602/doc-95-motion",
    html: page({
      title: "Letter motion for early termination of supervised release",
      site: "Court Docket Archive",
      published: "2023-11-29T17:00:00Z",
      body: `<p>Counsel respectfully requests early termination of supervised release.</p>
<p>The Second Circuit has repeatedly approved early termination. See ${FF}; ${OR}; ${AM}. Those decisions reflect sustained rehabilitation and comunity engagement after release, and show judges ending supervision early for defendants with a clean record.</p>`,
    }),
  },
  {
    url: "https://dockets.court-archive.test/cohen/18-cr-602/doc-97-order-to-show-cause",
    html: page({
      title: "Order to show cause",
      site: "Court Docket Archive",
      published: "2023-12-12T15:00:00Z",
      body: `<p>The <a href="https://dockets.court-archive.test/cohen/18-cr-602/doc-95-motion">November 29 motion</a> cites ${FF}, ${OR}, and ${AM}.</p>
<p>The Court has been unable to locate any of these three decisions. Counsel shall show cause why sanctions should not issue.</p>`,
    }),
  },
  {
    url: "https://docket-digest.test/2023/12/01/cohen-supervised-release",
    html: page({
      title: "Cohen asks court to end supervised release early",
      site: "The Docket Digest",
      body: `<p>Lawyers for Michael Cohen have asked a federal judge in Manhattan to end his supervised release early.</p>
<p>The <a href="https://dockets.court-archive.test/cohen/18-cr-602/doc-95-motion">motion</a> relies on ${FF}, ${OR}, and ${AM}, three Second Circuit decisions that it says granted early termination in similar circumstances.</p>`,
    }),
  },
  {
    url: "https://legal-wire.test/news/judge-questions-cohen-citations",
    search_published: "2023-12-13",
    html: page({
      title: "Judge says cases cited for Cohen do not appear to exist",
      site: "Legal Wire",
      published: "2023-12-13T15:00:00Z",
      body: `<p>A federal judge said he could not find ${FF}, ${OR}, or ${AM}, the cases cited in a motion filed for Michael Cohen, according to an <a href="https://dockets.court-archive.test/cohen/18-cr-602/doc-97-order-to-show-cause">order to show cause</a>.</p>`,
    }),
  },
  {
    url: "https://dockets.court-archive.test/cohen/18-cr-602/doc-102-cohen-declaration",
    html: page({
      title: "Declaration of Michael Cohen",
      site: "Court Docket Archive",
      published: "2023-12-28T16:00:00Z",
      body: `<p>In response to the <a href="https://dockets.court-archive.test/cohen/18-cr-602/doc-97-order-to-show-cause">order to show cause</a>, the defendant states that he found ${FF}, ${OR}, and ${AM} using Google Bard, which he understood to be an enhanced search tool, and did not know it could generate citations that do not exist.</p>`,
    }),
  },
  {
    url: "https://daily-ledger.test/2023/12/29/cohen-bard-fake-cases",
    html: page({
      title: "Cohen says AI chatbot supplied the fake cases",
      site: "The Daily Ledger",
      jsonLdDate: "2023-12-29T21:00:00Z",
      body: `<p>Michael Cohen said in a <a href="https://dockets.court-archive.test/cohen/18-cr-602/doc-102-cohen-declaration">court declaration</a> that the citations ${FF}, ${OR}, and ${AM} came from Google Bard.</p>
<p>Cohen said he did not realize the chatbot could invent case law that looked entirely plausible, and that he passed the cases to his lawyer without checking them.</p>
<p>Earlier this month the judge <a href="https://legal-wire.test/news/judge-questions-cohen-citations">questioned the citations</a>.</p>`,
    }),
  },
  {
    url: "https://lawtech-roundup.test/posts/ai-citations-week",
    html: page({
      title: "This week in AI and the courts",
      site: "LawTech Roundup",
      timeElement: "2024-01-05T09:00:00Z",
      body: `<p>More trouble with AI research tools. Michael Cohen admitted that ${FF}, ${OR}, and ${AM} came from a chatbot.</p>
<p>Cohen said he did not realize the chatbot could invent case law that looked entirely plausible, and that he passed the cases to his lawyer without checking them.</p>`,
    }),
  },
  {
    url: "https://forum.practitioners.test/t/cohen-bard-cases/4411",
    html: page({
      title: "Thread: the Cohen Bard cases",
      body: `<p>Has anyone pulled ${FF}, ${OR}, or ${AM}? Apparently none of them exist. See the <a href="https://daily-ledger.test/2023/12/29/cohen-bard-fake-cases">Daily Ledger story</a>.</p>`,
    }),
  },
  {
    url: "https://aggregator.test/archive/ai-cases-explainer",
    html: page({
      title: "Explainer: the fake Cohen cases",
      site: "Aggregator",
      published: "2023-10-01T00:00:00Z",
      body: `<p>The motion cited ${FF}, ${OR}, and ${AM}, describing sustained rehabilitation and comunity engagement after release.</p>
<p>As <a href="https://legal-wire.test/news/judge-questions-cohen-citations">Legal Wire reported</a>, the judge could not find them.</p>`,
    }),
  },
  {
    url: "https://ai-hallucination-tracker.test/cases/cohen",
    html: page({
      title: "AI hallucination tracker: Cohen",
      site: "AI Hallucination Tracker",
      published: "2024-02-10T12:00:00Z",
      body: `<p>Fabricated citations: ${FF}, ${OR}, ${AM}.</p>
<p>Sources: <a href="https://legal-wire.test/news/judge-questions-cohen-citations">Legal Wire</a>, <a href="https://daily-ledger.test/2023/12/29/cohen-bard-fake-cases">The Daily Ledger</a>. Compare <a href="https://legal-wire.test/news/lawyers-sanctioned-chatgpt-avianca">the Avianca case</a>.</p>`,
    }),
  },

  // --- Decoys ----------------------------------------------------------------------------
  {
    url: "https://legal-wire.test/news/lawyers-sanctioned-chatgpt-avianca",
    html: page({
      title: "Lawyers sanctioned for fake cases generated by ChatGPT",
      site: "Legal Wire",
      published: "2023-06-22T18:00:00Z",
      body: `<p>Two lawyers were sanctioned after a brief in Mata v. Avianca cited fake cases generated by the AI chatbot ChatGPT, including Varghese v. China Southern Airlines.</p>
<p>The judge said the fake cases looked plausible but did not exist, a warning for lawyers using AI research tools.</p>`,
    }),
  },
  {
    url: "https://opinions.appeals.test/2021/united-states-v-ortiz",
    html: page({
      title: `${OR} (suppression appeal)`,
      site: "Appellate Opinions",
      published: "2021-03-15T12:00:00Z",
      body: `<p>In ${OR}, the court affirmed the denial of a motion to suppress evidence found during a traffic stop.</p>
<p>The defendant, who was on supervised release at the time, argued the stop lacked reasonable suspicion.</p>`,
    }),
  },
  {
    url: "https://daily-ledger.test/2023/11/30/cohen-seeks-early-end-to-supervision",
    html: page({
      title: "Cohen seeks early end to supervision",
      site: "The Daily Ledger",
      jsonLdDate: "2023-11-30T20:00:00Z",
      body: `<p>Michael Cohen asked a federal judge to end his supervised release early, citing his compliance with every condition since leaving prison.</p>
<p>His lawyer argued that courts have approved early termination for defendants with a clean record.</p>`,
    }),
  },
];
